### PR TITLE
Support querying and updating UniFi Networks

### PR DESCRIPTION
**Pull request by KyleBrandon**
Added INetwork.ts to provide a contract for the Network entity Added Network.ts to represent a network in UniFi
Added Networks.ts to allow for querying all existing networks Updated Controller.ts to provide API to getNetworks
Add "networks" API to the IController interface

## :memo: Description
This adds functionality to query a list of UniFi Networks as listed under the UnFi Settings > Networks console.  The desire was to utilize this library to build a Homebridge plugin that allows one to surface the UDM gateway and the networks in HomeKit. This then allows one to enable or disable the entire Network via HomeKit and control it via automations.  This fulfilled a need of mine as I have a certain member of my family entirely relegated to a separate VLAN network due to the propensity to click on just about anything.  I am able to easily enable and disable their internet connectivity when it's time to turn off. 

### :dart: Relevant issues
None that I'm aware of

### :gem: Type of change

- [x ] New feature (non-breaking change which adds functionality)

### :scroll: Example code
```js
await controller.login();
const [site] = await controller.sites.list();
const networks = await site.networks.list();
const [network] = networks.filter(
    (network) => network.name === "Brandon IoT",
);
network.enabled = true;
await network.save();
``` 

## :vertical_traffic_light: How Has This Been Tested?

Manual testing was performed in the fashion listed in the example above as well as using it within the Homebridge plugin.  I was unable to get the existing integration tests to run successfully so I was not able to add to the test suite.
I did verify that the Network object returned was equivalent to the returned in the browser while monitoring traffic of the UniFi Network console.

I also based this code off the Site and Device implementations.

## :checkered_flag: Checklist:

- [ x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by KyleBrandon** [comment]
@thib3113 any direction you can point me in for addressing these errors?  Some of the errors are:

`'snyk' requires an authenticated account. Please run 'snyk auth' and try again.`
This seems to indicate either I or the integration needs an account configured?


` Error: Resource not accessible by integration `
It looks like everything succeeded but it wasn't able to reach 'https://api.github.com/repos/thib3113/unifi-client/check-runs'.

Happy to dig in but I'm new to some of these integrations!

Kind regards, 
Kyle

**Comment by thib3113** [comment]
@KyleBrandon It's a right problem :) . You don't have access to the repositories secrets . That's why :) . 

I need to dig on it :) . 

About the jest automated, you can see just before the http error : 
```
Check payload: {"owner":"thib3113","repo":"unifi-client","head_sha":"23240b14c2c1011fdde0c38e1532467c5dae872c","name":"jest-github-action","status":"completed","conclusion":"success","output":{"title":"Jest tests passed","summary":"594 tests passing in 28 suites.","annotations":[]}}
```
( this json is the important part . all the tests succeeds ) . 

About the tests, I need to dig on them too ... Sometimes, they are crashing on my side too (and some time with an unreadable erorr that I always failed to reproduce) ... I need to spend some time on this  (but didn't have the time now)

**Comment by KyleBrandon** [comment]
Ahh that makes sense. Would it help if I sent the error output from my test run?  

<Removed cruft from replaying via email>

**Comment by thib3113** [comment]
( think about editing your messages if you answer by mail to make it more readable . And I didn't recommend answering with mail, because it can expose private informations )


yes, the message can maybe help ... but I'm not sure I can't do it this week / week end ...

**Comment by KyleBrandon** [comment]
Here is the json output for the test run.  
[test.log](https://github.com/thib3113/unifi-client/files/12171602/test.log)

Let me know if there's anything else I can do!

Kind regards,
Kyle

**Comment by thib3113** [comment]
@KyleBrandon if I correctly remember, "tests scenario" need a real machine (you can emulate non unifios with unifi controller from docker . But emulating unifios is harder) . or the mocks from nock ... I know there is a way to update the nock mocks, but I don't remember exactly how ... 

So, I think the tests failed because the mock doesn't exists, or doesn't match the mock .

**Comment by KyleBrandon** [comment]
I thought that might be the case.  I tried configuring the TEST_* environment variables defined in src/test.js, however that didn't work.  I'm not certain if it excepted my UDM to be configured in a certain way.  I've also tried running the npm "generate" scripts but that didn't help either.

I'll keep playing with it but at this point, I'm at a loss as far as getting the other tests passing.  I'll move this PR out of draft, and if there's anything else you need, please let me know.

Kyle

**Comment by thib3113** [comment]
@KyleBrandon Can you try to write only unit tests ? ( pretty sure you can run them ... or by passing a path to jest ) .

I didn't know when I can generate the datas (lot of work now) ...

**Comment by KyleBrandon** [comment]
Yes, I'll get those in and resubmit.

Kyle

**Pull request closed without merging**
